create database customer_behaviour;
use customer_behaviour;
select*from mytable;
#1 what is the total revenue generated by male vs female customer
select gender,sum(purchase_amount) as revenue from mytable 
group by gender;

#2 which customer used a discount but still spent more than the average purchase amount?
select customer_id,purchase_amount,discount_applied from mytable
where discount_applied="yes" and
purchase_amount>(select avg(purchase_amount)from mytable);

# 3 which are the top 5 products with the highest average review ratings?
select item_purchased,round(avg(review_rating),2) from mytable group by item_purchased 
order by avg(review_rating) desc limit 5;

# 4 compare the average purchase amounts between standard and express shipping?
select shipping_type,round(avg(purchase_amount),2) as compare_avg_amount from mytable where shipping_type 
in ('standard','express') group by shipping_type;
 #5 Do subscribed customers spend more? compare avearge spend and total revenue between subscribers 
 # and non subscribers.
 select subscription_status,count(customer_id) as total_customer,
 round(avg(purchase_amount),2) as total_spend,
 round(sum(purchase_amount),2) as total_revenue from mytable group by subscription_status;
 
 #6 which 5 products have highest precentage of purchases with discount applied?
 
select item_purchased,round(100*sum(case when discount_applied='yes' then 1 else 0 end)/count(*),2) as 
discount_rate from mytable group by item_purchased order by discount_rate desc limit 5;
 
# 7 segment customers into new , returning and loyal based on their total number 
#of previous purchases and show the count of each segment.

with customer_type as (select customer_id,previous_purchases, case when
previous_purchases=1 then 'new' when previous_purchases between 2 and 10 then 'returning' 
else 'loyal'  end as customer_segment from mytable) 
select customer_segment,count(*)
as "number_of_customer" from customer_type group by customer_segment;

# 8 what are the top3 most purchased products within each categeory.
with item_counts as(select category,item_purchased,count(customer_id) as total_orders,
row_number() over(partition by category order by count(customer_id) Desc) as item_rank 
from mytable group by category,item_purchased)
select item_rank,category,item_purchased,total_orders from item_counts where
item_rank <=3;

#9 Are customers who are repeat buyers( more than 5 previous purchases) ,
#also likely to subscribe.
select subscription_status,count(customer_id) as repeat_buyers from mytable
where previous_purchases>5 group by subscription_status;

# 10 what is the revenue contribution of each age group;
select age_group,sum(purchase_amount) as total_revenue from mytable 
group by age_group order by total_revenue desc;


